<?php

namespace Markette\Gopay\Api;


/**
 * Trida obsahuje kody pro jednotlive staty
 */
class CountryCode {
    const ABW = "ABW"; //Aruba
    const AFG = "AFG"; //Afghanistan
    const AGO = "AGO"; //Angola
    const AIA = "AIA"; //Anguilla
    const ALA = "ALA"; //Åland Islands
    const ALB = "ALB"; //Albania
    const ARE = "ARE"; //United Arab Emirates
    const ARG = "ARG"; //Argentina
    const ARM = "ARM"; //Armenia
    const ASM = "ASM"; //American Samoa
    const ATA = "ATA"; //Antarctica
    const ATF = "ATF"; //French Southern Territories
    const ATG = "ATG"; //Antigua and Barbuda
    const AUS = "AUS"; //Australia
    const AUT = "AUT"; //Austria
    const AZE = "AZE"; //Azerbaijan
    const BDI = "BDI"; //Burundi
    const BEL = "BEL"; //Belgium
    const BEN = "BEN"; //Benin
    const BES = "BES"; //Bonaire, Sint Eustatius and Saba
    const BFA = "BFA"; //Burkina Faso
    const BGD = "BGD"; //Bangladesh
    const BGR = "BGR"; //Bulgaria
    const BHR = "BHR"; //Bahrain
    const BHS = "BHS"; //Bahamas
    const BIH = "BIH"; //Bosnia and Herzegovina
    const BLM = "BLM"; //Saint Barthélemy
    const BLR = "BLR"; //Belarus
    const BLZ = "BLZ"; //Belize
    const BMU = "BMU"; //Bermuda
    const BOL = "BOL"; //Bolivia, Plurinational State of
    const BRA = "BRA"; //Brazil
    const BRB = "BRB"; //Barbados
    const BRN = "BRN"; //Brunei Darussalam
    const BTN = "BTN"; //Bhutan
    const BVT = "BVT"; //Bouvet Island
    const BWA = "BWA"; //Botswana
    const CAF = "CAF"; //Central African Republic
    const CAN = "CAN"; //Canada
    const CCK = "CCK"; //Cocos (Keeling) Islands
    const CHE = "CHE"; //Switzerland
    const CHL = "CHL"; //Chile
    const CHN = "CHN"; //China
    const CIV = "CIV"; //Côte d'Ivoire
    const CMR = "CMR"; //Cameroon
    const COD = "COD"; //Congo, the Democratic Republic of the
    const COG = "COG"; //Congo
    const COK = "COK"; //Cook Islands
    const COL = "COL"; //Colombia
    const COM = "COM"; //Comoros
    const CPV = "CPV"; //Cape Verde
    const CRI = "CRI"; //Costa Rica
    const CUB = "CUB"; //Cuba
    const CUW = "CUW"; //Curaçao
    const CXR = "CXR"; //Christmas Island
    const CYM = "CYM"; //Cayman Islands
    const CYP = "CYP"; //Cyprus
    const CZE = "CZE"; //Czech Republic
    const DEU = "DEU"; //Germany
    const DJI = "DJI"; //Djibouti
    const DMA = "DMA"; //Dominica
    const DNK = "DNK"; //Denmark
    const DOM = "DOM"; //Dominican Republic
    const DZA = "DZA"; //Algeria
    const ECU = "ECU"; //Ecuador
    const EGY = "EGY"; //Egypt
    const ERI = "ERI"; //Eritrea
    const ESH = "ESH"; //Western Sahara
    const ESP = "ESP"; //Spain
    const EST = "EST"; //Estonia
    const ETH = "ETH"; //Ethiopia
    const FIN = "FIN"; //Finland
    const FJI = "FJI"; //Fiji
    const FLK = "FLK"; //Falkland Islands (Malvinas)
    const FRA = "FRA"; //France
    const FRO = "FRO"; //Faroe Islands
    const FSM = "FSM"; //Micronesia, Federated States of
    const GAB = "GAB"; //Gabon
    const GBR = "GBR"; //United Kingdom
    const GEO = "GEO"; //Georgia
    const GGY = "GGY"; //Guernsey
    const GHA = "GHA"; //Ghana
    const GIB = "GIB"; //Gibraltar
    const GIN = "GIN"; //Guinea
    const GLP = "GLP"; //Guadeloupe
    const GMB = "GMB"; //Gambia
    const GNB = "GNB"; //Guinea-Bissau
    const GNQ = "GNQ"; //Equatorial Guinea
    const GRC = "GRC"; //Greece
    const GRD = "GRD"; //Grenada
    const GRL = "GRL"; //Greenland
    const GTM = "GTM"; //Guatemala
    const GUF = "GUF"; //French Guiana
    const GUM = "GUM"; //Guam
    const GUY = "GUY"; //Guyana
    const HKG = "HKG"; //Hong Kong
    const HMD = "HMD"; //Heard Island and McDonald Islands
    const HND = "HND"; //Honduras
    const HRV = "HRV"; //Croatia
    const HTI = "HTI"; //Haiti
    const HUN = "HUN"; //Hungary
    const IDN = "IDN"; //Indonesia
    const IMN = "IMN"; //Isle of Man
    const IND = "IND"; //India
    const IOT = "IOT"; //British Indian Ocean Territory
    const IRL = "IRL"; //Ireland
    const IRN = "IRN"; //Iran, Islamic Republic of
    const IRQ = "IRQ"; //Iraq
    const ISL = "ISL"; //Iceland
    const ISR = "ISR"; //Israel
    const ITA = "ITA"; //Italy
    const JAM = "JAM"; //Jamaica
    const JEY = "JEY"; //Jersey
    const JOR = "JOR"; //Jordan
    const JPN = "JPN"; //Japan
    const KAZ = "KAZ"; //Kazakhstan
    const KEN = "KEN"; //Kenya
    const KGZ = "KGZ"; //Kyrgyzstan
    const KHM = "KHM"; //Cambodia
    const KIR = "KIR"; //Kiribati
    const KNA = "KNA"; //Saint Kitts and Nevis
    const KOR = "KOR"; //Korea, Republic of
    const KWT = "KWT"; //Kuwait
    const LAO = "LAO"; //Lao People's Democratic Republic
    const LBN = "LBN"; //Lebanon
    const LBR = "LBR"; //Liberia
    const LBY = "LBY"; //Libyan Arab Jamahiriya
    const LCA = "LCA"; //Saint Lucia
    const LIE = "LIE"; //Liechtenstein
    const LKA = "LKA"; //Sri Lanka
    const LSO = "LSO"; //Lesotho
    const LTU = "LTU"; //Lithuania
    const LUX = "LUX"; //Luxembourg
    const LVA = "LVA"; //Latvia
    const MAC = "MAC"; //Macao
    const MAF = "MAF"; //Saint Martin (French part)
    const MAR = "MAR"; //Morocco
    const MCO = "MCO"; //Monaco
    const MDA = "MDA"; //Moldova, Republic of
    const MDG = "MDG"; //Madagascar
    const MDV = "MDV"; //Maldives
    const MEX = "MEX"; //Mexico
    const MHL = "MHL"; //Marshall Islands
    const MKD = "MKD"; //Macedonia, the former Yugoslav Republic of
    const MLI = "MLI"; //Mali
    const MLT = "MLT"; //Malta
    const MMR = "MMR"; //Myanmar
    const MNE = "MNE"; //Montenegro
    const MNG = "MNG"; //Mongolia
    const MNP = "MNP"; //Northern Mariana Islands
    const MOZ = "MOZ"; //Mozambique
    const MRT = "MRT"; //Mauritania
    const MSR = "MSR"; //Montserrat
    const MTQ = "MTQ"; //Martinique
    const MUS = "MUS"; //Mauritius
    const MWI = "MWI"; //Malawi
    const MYS = "MYS"; //Malaysia
    const MYT = "MYT"; //Mayotte
    const NAM = "NAM"; //Namibia
    const NCL = "NCL"; //New Caledonia
    const NER = "NER"; //Niger
    const NFK = "NFK"; //Norfolk Island
    const NGA = "NGA"; //Nigeria
    const NIC = "NIC"; //Nicaragua
    const NIU = "NIU"; //Niue
    const NLD = "NLD"; //Netherlands
    const NOR = "NOR"; //Norway
    const NPL = "NPL"; //Nepal
    const NRU = "NRU"; //Nauru
    const NZL = "NZL"; //New Zealand
    const OMN = "OMN"; //Oman
    const PAK = "PAK"; //Pakistan
    const PAN = "PAN"; //Panama
    const PCN = "PCN"; //Pitcairn
    const PER = "PER"; //Peru
    const PHL = "PHL"; //Philippines
    const PLW = "PLW"; //Palau
    const PNG = "PNG"; //Papua New Guinea
    const POL = "POL"; //Poland
    const PRI = "PRI"; //Puerto Rico
    const PRK = "PRK"; //Korea, Democratic People's Republic of
    const PRT = "PRT"; //Portugal
    const PRY = "PRY"; //Paraguay
    const PSE = "PSE"; //Palestinian Territory, Occupied
    const PYF = "PYF"; //French Polynesia
    const QAT = "QAT"; //Qatar
    const REU = "REU"; //Réunion
    const ROU = "ROU"; //Romania
    const RUS = "RUS"; //Russian Federation
    const RWA = "RWA"; //Rwanda
    const SAU = "SAU"; //Saudi Arabia
    const SDN = "SDN"; //Sudan
    const SEN = "SEN"; //Senegal
    const SGP = "SGP"; //Singapore
    const SGS = "SGS"; //South Georgia and the South Sandwich Islands
    const SHN = "SHN"; //Saint Helena, Ascension and Tristan da Cunha
    const SJM = "SJM"; //Svalbard and Jan Mayen
    const SLB = "SLB"; //Solomon Islands
    const SLE = "SLE"; //Sierra Leone
    const SLV = "SLV"; //El Salvador
    const SMR = "SMR"; //San Marino
    const SOM = "SOM"; //Somalia
    const SPM = "SPM"; //Saint Pierre and Miquelon
    const SRB = "SRB"; //Serbia
    const SSD = "SSD"; //South Sudan
    const STP = "STP"; //Sao Tome and Principe
    const SUR = "SUR"; //Suriname
    const SVK = "SVK"; //Slovakia
    const SVN = "SVN"; //Slovenia
    const SWE = "SWE"; //Sweden
    const SWZ = "SWZ"; //Swaziland
    const SXM = "SXM"; //Sint Maarten (Dutch part)
    const SYC = "SYC"; //Seychelles
    const SYR = "SYR"; //Syrian Arab Republic
    const TCA = "TCA"; //Turks and Caicos Islands
    const TCD = "TCD"; //Chad
    const TGO = "TGO"; //Togo
    const THA = "THA"; //Thailand
    const TJK = "TJK"; //Tajikistan
    const TKL = "TKL"; //Tokelau
    const TKM = "TKM"; //Turkmenistan
    const TLS = "TLS"; //Timor-Leste
    const TON = "TON"; //Tonga
    const TTO = "TTO"; //Trinidad and Tobago
    const TUN = "TUN"; //Tunisia
    const TUR = "TUR"; //Turkey
    const TUV = "TUV"; //Tuvalu
    const TWN = "TWN"; //Taiwan, Province of China
    const TZA = "TZA"; //Tanzania, United Republic of
    const UGA = "UGA"; //Uganda
    const UKR = "UKR"; //Ukraine
    const UMI = "UMI"; //United States Minor Outlying Islands
    const URY = "URY"; //Uruguay
    const USA = "USA"; //United States
    const UZB = "UZB"; //Uzbekistan
    const VAT = "VAT"; //Holy See (Vatican City State)
    const VCT = "VCT"; //Saint Vincent and the Grenadines
    const VEN = "VEN"; //Venezuela, Bolivarian Republic of
    const VGB = "VGB"; //Virgin Islands, British
    const VIR = "VIR"; //Virgin Islands, U.S.
    const VNM = "VNM"; //Viet Nam
    const VUT = "VUT"; //Vanuatu
    const WLF = "WLF"; //Wallis and Futuna
    const WSM = "WSM"; //Samoa
    const YEM = "YEM"; //Yemen
    const ZAF = "ZAF"; //South Africa
    const ZMB = "ZMB"; //Zambia
    const ZWE = "ZWE"; //Zimbabwe 
}
